# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress=https://localhost:5001
@BearerToken=<YourToken>

@Email=administrator@localhost
@Password=Administrator1!

### @name health
GET {{Web_HostAddress}}/health
Accept: application/json

### @name auth_login
POST {{Web_HostAddress}}/api/Auth/Login
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}